
###
GET http://localhost:5000/api/product HTTP/1.1
###
POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "wahedm@gmail9.com",
    "password": "1234579444"
}

###
POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "email": "jssss@gmail.com",
    "password": "123457944411",
    "name":"wahed mjssss",
    "phoneNumber":"09982471588"
}

###
POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "jssss@gmail.com",
    "password": "123457944411"
}